# src/main/resources/application.yml
spring:
  application:
    name: demo1  # 应用名称，用于服务注册与发现
  datasource:
    url: jdbc:mysql://localhost:3306/msb?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080  # 服务端口